runtime: nodejs20
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  REACT_APP_ENV: prod

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build